# Generated by Django 3.2.5 on 2024-06-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_auto_20240607_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default='NULL', null=True),
        ),
    ]
