# Generated by Django 3.2.5 on 2024-06-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_alter_book_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
