# Generated by Django 3.2.5 on 2024-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0004_alter_rental_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default='2020-09-10', null=True),
        ),
    ]
